data_path: "dataset/preproceessed"
output_base: "output"
seed: !!int 0
encoders:
  - "bert-base-uncased"
learning_rates:
  - !!float 2e-5
lambda_weights:
  - !!float 0.25
batch_size: !!int 8
num_epochs: !!int 6
data_mains:
  - name: "ihc"
    methods:
      - name: "cam"
        cam_angular_margins_m:
          - !!float 1.57
        cam_lambda_as:
          - !!float 0.75
        cam_lambda_rs:
          - !!float 0.5
