data_path: "dataset/preproceessed"
output_base: "output.contrastive"
seed: !!int 0
encoders:
  - "bert-base-uncased"
learning_rates:
  - !!float 2e-5
lambda_weights:
  - !!float 0.25
batch_size: !!int 8
num_epochs: !!int 6
data_mains:
  - name: "ihc"
    methods:
      - name: "contrastive"
        temperatures: [!!float 0.3]
  - name: "sbic"
    methods:
      - name: "contrastive"
        temperatures: [!!float 0.3]
