data_path: "dataset/preproceessed"
output_base: "output"
seed: !!int 0
encoders:
  - "bert-base-uncased"
learning_rates:
  - !!float 2e-5
lambda_weights:
  - !!float 0.25
batch_size: !!int 8
num_epochs: !!int 6
data_mains:
  - name: "ihc"
    methods:
      - name: "semi-hard"
        d_fn: ["cos_f"]
        angular_margin: [!!float 0.4]
        fallback: [!!bool true]
        margins: [!!float 0.3]
        reducers:
          - name: "sm_learnable"
            beta: [!!float 10]
