data_path: "dataset/preproceessed"
output_base: "output"
seed: !!int 0
encoders:
  - "bert-base-uncased"
learning_rates:
  - !!float 2e-5
lambda_weights:
  - !!float 0.25
batch_size: !!int 8
num_epochs: !!int 6
data_mains:
  - name: "ihc"
    methods:
      - name: "semi-hard"
        fallback: [!!bool true]
        margins: [!!float 0.3]
        reducers:
          - name: "softmax"
            beta_values: [!!int 15]
  # - name: "sbic"
  #   methods:
  #     - name: "semi-hard"
  #       fallback: [!!bool true]
  #       margins: [!!float 0.45]
  #       reducers:
  #         - name: "softmax"
  #           beta_values: [!!int 5]
# Learning rates      : 2e-5
# reducers            : softmax
# lambda weights      : 0.25

# Fallback            : True

# IHC   #
# beta                : 15
# Margin              : 0.3

# SBIC  #
# beta                : 5
# Margin              : 0.45
